### CREATE a product
POST http://localhost:3000/products
Content-Type: application/json

{
    "productType": "Papel Higienico",
    "brand": "Higienol",
    "lineUp": "Pro Max",
    "description": "4x80 mts / 10 ppaquetes por bolson.",
    "stock": "10",
    "price": "2300",
    "isActive": "true"
} 