### CREATE a product
POST http://localhost:3000/products
Content-Type: application/json

{
    "productType": "df higienico",
    "brand": "",
    "lineUp": "sdfsfs",
    "description": "Papel Higienico",
    "stock": "10",
    "price": "2342",
    "isActive": "sdss"
} 